# Generated by Django 4.1.7 on 2024-11-18 09:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày khởi tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_active', models.BooleanField(default=True, help_text='Chỉ định xem đối tượng này còn được coi là đang hoạt động. Bạn nên bỏ chọn này thay vì xóa đối tượng.', verbose_name='Hoạt động')),
                ('file', models.FileField(upload_to='media/%Y/%m/%d')),
            ],
        ),
    ]
